CREATE TABLE quotation (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    quotation_no VARCHAR(50) NOT NULL COMMENT '报价单号',
    policy_id BIGINT COMMENT '关联策略(快照源)',
    opportunity_id BIGINT COMMENT '关联商机ID',
    tax_mode VARCHAR(20) NOT NULL COMMENT '计税模式: TAX_INCLUDED/TAX_EXCLUDED',
    customer_name VARCHAR(200) COMMENT '委托方/品牌公司名称',
    contact_person VARCHAR(100) COMMENT '项目负责人',
    contact_phone VARCHAR(50) COMMENT '电话',
    contact_email VARCHAR(200) COMMENT '邮件',
    delivery_period VARCHAR(100) COMMENT '交货期',
    quote_date DATE NOT NULL COMMENT '报价日期',
    validity_days INT NOT NULL DEFAULT 30 COMMENT '报价有效期(天)',
    currency VARCHAR(20) NOT NULL DEFAULT 'CNY' COMMENT '货币种类',
    invoice_type VARCHAR(50) NOT NULL DEFAULT '增值税专用发票' COMMENT '发票类型',
    first_year_total_ex_tax DECIMAL(15,2) COMMENT '首年未税总价',
    first_year_total_incl_tax DECIMAL(15,2) COMMENT '首年含税总价',
    subsequent_year_total_ex_tax DECIMAL(15,2) COMMENT '次年及以后未税总价',
    subsequent_year_total_incl_tax DECIMAL(15,2) COMMENT '次年及以后含税总价',
    quotation_note TEXT COMMENT '报价说明(自动填充模板条款)',
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT '状态: DRAFT/INTERNAL_REVIEW/APPROVED/SENT/ACCEPTED/REJECTED/EXPIRED',
    created_by VARCHAR(100) COMMENT '创建人',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_quotation_no (quotation_no),
    INDEX idx_q_opportunity_id (opportunity_id),
    INDEX idx_q_status (status),
    INDEX idx_q_customer_name (customer_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报价单';