/**
 * 迁移期路由白名单：只注册已经接入真实业务接口的页面。
 * 未迁移模块继续由旧 Vue 工程承载，避免用 Pro 示例页面冒充功能。
 */
export default [
  {
    path: '/user',
    layout: false,
    routes: [
      { path: '/user/login', component: './user/login' },
      { path: '/user', redirect: '/user/login' },
    ],
  },
  { path: '/login', layout: false, redirect: '/user/login' },
  {
    path: '/workbench',
    name: '工作台',
    icon: 'appstore',
    component: './workbench',
  },
  {
    path: '/requirements',
    name: '需求管理',
    icon: 'fileText',
    component: './requirements',
  },
  {
    path: '/requirements/:id',
    name: '需求详情',
    hideInMenu: true,
    component: './requirements',
  },
  {
    path: '/requirements-standalone/:id',
    name: '需求详情（独立页）',
    hideInMenu: true,
    component: './requirements',
  },
  {
    path: '/meetings',
    name: '会议管理',
    icon: 'timer',
    component: './meetings',
  },
  {
    path: '/meetings/:id',
    name: '会议详情',
    hideInMenu: true,
    component: './meetings',
  },
  {
    path: '/schedule',
    name: '日程',
    icon: 'Calendar',
    component: './schedule',
  },
  {
    path: '/tasks',
    name: '任务管理',
    icon: 'checkSquare',
    component: './tasks',
  },
  {
    path: '/defects',
    name: '缺陷管理',
    icon: 'closeCircle',
    component: './defects',
  },
  {
    path: '/todos',
    name: '待办',
    icon: 'checkCircle',
    component: './todos',
  },
  {
    path: '/weekly-report',
    name: '周报中心',
    icon: 'profile',
    component: './weekly-report',
  },
  {
    path: '/business-lines',
    name: '业务线管理',
    icon: 'apartment',
    component: './business-lines',
  },
  { path: '/organization', redirect: '/business-lines' },
  {
    path: '/projects',
    name: '项目管理',
    icon: 'folderOpen',
    component: './projects',
  },
  {
    path: '/customers',
    name: '客户信息管理',
    icon: 'contacts',
    component: './customers',
  },
  {
    path: '/opportunities',
    name: '线索商机管理',
    icon: 'rise',
    component: './opportunities',
  },
  {
    path: '/quotation-policies',
    name: '报价策略管理',
    icon: 'sliders',
    component: './quotation-policies',
  },
  {
    path: '/quotations',
    name: '报价单管理',
    icon: 'fileText',
    component: './quotations',
  },
  {
    path: '/quotations/:id',
    name: '报价单详情',
    hideInMenu: true,
    component: './quotations',
  },
  {
    path: '/system/users',
    name: '用户管理',
    icon: 'team',
    component: './system-users',
  },
  {
    path: '/system/roles',
    name: '角色管理',
    icon: 'safety',
    component: './system-roles',
  },
  {
    path: '/system/menus',
    name: '菜单管理',
    icon: 'menu',
    component: './system-menus',
  },
  {
    path: '/system/permissions',
    name: '权限管理',
    icon: 'lock',
    component: './system-permissions',
  },
  {
    path: '/system/workflow',
    name: '工作流配置',
    icon: 'branches',
    component: './system-workflow',
  },
  {
    path: '/system/configs',
    name: '配置管理',
    icon: 'setting',
    component: './system-configs',
  },
  {
    path: '/system/connectors',
    name: '连接器管理',
    icon: 'api',
    component: './connectors',
  },
  {
    path: '/system/models',
    name: '模型管理',
    icon: 'ChatDotRound',
    component: './models',
  },
  { path: '/ai-connectors', redirect: '/system/connectors' },
  {
    path: '/system/sync',
    name: '数据集成中心',
    icon: 'cloudSync',
    component: './system-sync',
  },
  {
    path: '/ai-assistant',
    name: 'AI 助手',
    icon: 'message',
    component: './ai-assistant',
  },
  { path: '/emails', name: '邮件管理', icon: 'mail', component: './emails' },
  {
    path: '/key-matters',
    name: '大事儿管理',
    icon: 'flag',
    component: './key-matters',
  },
  {
    path: '/key-matters-meeting',
    name: '大事儿会议视图',
    icon: 'calendar',
    component: './key-matters',
  },
  {
    path: '/statistics',
    name: 'BU 驾驶舱',
    icon: 'dashboard',
    component: './statistics',
  },
  { path: '/revenue', redirect: '/revenue/worktime' },
  {
    path: '/revenue/worktime',
    name: '工时 & 成本',
    hideInMenu: true,
    component: './revenue',
  },
  {
    path: '/revenue/delivery',
    name: '交付与利润',
    hideInMenu: true,
    component: './revenue',
  },
  {
    path: '/revenue/delivery-confirm',
    name: '待交付确认',
    hideInMenu: true,
    component: './revenue',
  },
  {
    path: '/revenue/import',
    name: '数据导入',
    hideInMenu: true,
    component: './revenue',
  },
  {
    path: '/revenue/pending',
    name: '待映射与销售项目',
    hideInMenu: true,
    component: './revenue',
  },
  {
    path: '/kpi-report',
    name: 'KPI 周报',
    icon: 'lineChart',
    component: './kpi-report',
  },
  {
    path: '/oa-affairs',
    name: 'OA 待办',
    icon: 'checkCircle',
    component: './oa-affairs',
  },
  {
    path: '/bl-profit',
    name: '业务线利润',
    icon: 'fund',
    component: './bl-profit',
  },
  {
    path: '/project-profit',
    name: '项目利润',
    icon: 'fund',
    component: './project-profit',
  },
  { path: '/', redirect: '/workbench' },
  { path: '/*', redirect: '/workbench' },
];
